version: '3.8'

networks:
  network-project:
    driver: bridge

services:
  my_postgres:
    image: postgres
    ports: 
      - "5434:5432"
    networks:
      - network-project
    container_name: my_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ifrn.cn
      POSTGRES_DB: teste

  back:
    image: xicoxavier/back-image:latest
    ports: 
      - "3000:3000"
    restart: always
    networks:
      - network-project
    container_name: back
  front:
    image: xicoxavier/front-image:latest
    ports:
      - "8080:80"
    restart: always
    networks:
      - network-project
    container_name: front